Format target added and Improved test target
mongoose-os/mos pull request #43
Opened 2020-12-18 18:13 UTC by harens

[black](https://github.com/psf/black) has been used to format the python files, whilst [go fmt](https://golang.org/cmd/go/#hdr-Gofmt__reformat__package_sources) has been used for the go files.

Tests have also been written to make sure that the files have been formatted accordingly following a PR/commit.

2020-12-18 18:25 UTC, harens commented
Forgot that version/version.go is auto-generated, and so not formatted

2020-12-18 23:47 UTC, rojer requested changes

2020-12-18 23:47 UTC, rojer commented on tools/make_release_tags.py
> +        print(
i don't like this.
```
it's
    so
            damn
        verbose
```

2020-12-18 23:47 UTC, rojer commented on cli/bindata.go
> +	"github.com/elazarl/go-bindata-assetfs"
please split system imports from external, this kind of grouping doesn't make sense.

2020-12-19 12:23 UTC, harens commented
Thanks @rojer for the review. With second thoughts I think that this is too large a PR anyway, and it might be better to have smaller PRs for each change.

2020-12-19 12:23 UTC, closed without merging